#!/bin/bash

db=${1:-ces.sqlite}
topdir=${2:-cestats}

set -eu

cd "$(dirname "$0")"


select_into() {
	outfile=$1
	shift
	header=
	if [[ $1 = -header ]]; then
		header=-header
		shift
	fi
	sqlite3 -bail -separator $'\t' $header \
		"$db" \
		"SELECT DISTINCT $*;" \
		> "$topdir/$outfile.tab"
}


if [[ ! -f $db ]]; then
	echo "$db missing"
	exit 1
fi


mkdir -p "$topdir/fqdns/"{topo,fact,join,topo-not-fact,fact-not-topo}
mkdir -p "$topdir/facilities/"{topo,join}
find "$topdir/" -type f -name \*.tab -exec rm -f {} +

select_into fqdns/topo/active-prod-us     "fqdn FROM topology WHERE active=1 AND prod=1 AND us=1     ORDER BY fqdn"
select_into fqdns/topo/active-prod-nonus  "fqdn FROM topology WHERE active=1 AND prod=1 AND us=0     ORDER BY fqdn"
select_into fqdns/topo/active-prod-hosted "fqdn FROM topology WHERE active=1 AND prod=1 AND hosted=1 ORDER BY fqdn"
select_into fqdns/fact/active-prod-us     "fqdn FROM factory WHERE enabled=1 AND prod=1 AND us=1     ORDER BY fqdn"
select_into fqdns/fact/active-prod-nonus  "fqdn FROM factory WHERE enabled=1 AND prod=1 AND us=0     ORDER BY fqdn"
select_into fqdns/fact/active-prod-hosted "fqdn FROM factory WHERE enabled=1 AND prod=1 AND hosted=1 ORDER BY fqdn"

select_into facilities/topo/active-prod-us     "r.facility FROM topology AS t JOIN resourcegroup AS r ON t.resourcegroup = r.name WHERE t.active=1 AND t.prod=1 AND t.us=1     ORDER BY r.facility"
select_into facilities/topo/active-prod-nonus  "r.facility FROM topology AS t JOIN resourcegroup AS r ON t.resourcegroup = r.name WHERE t.active=1 AND t.prod=1 AND t.us=0     ORDER BY r.facility"
select_into facilities/topo/active-prod-hosted "r.facility FROM topology AS t JOIN resourcegroup AS r ON t.resourcegroup = r.name WHERE t.active=1 AND t.prod=1 AND t.hosted=1 ORDER BY r.facility"

select_into fqdns/join/active-prod-us         "t.fqdn FROM topology AS t JOIN factory AS f USING(fqdn) WHERE t.active=1 AND f.enabled=1 AND t.prod=1 AND f.prod=1 AND t.us=1     ORDER BY t.fqdn"
select_into fqdns/join/active-prod-nonus      "t.fqdn FROM topology AS t JOIN factory AS f USING(fqdn) WHERE t.active=1 AND f.enabled=1 AND t.prod=1 AND f.prod=1 AND t.us=0     ORDER BY t.fqdn"
select_into fqdns/join/active-prod-hosted     "t.fqdn FROM topology AS t JOIN factory AS f USING(fqdn) WHERE t.active=1 AND f.enabled=1 AND t.prod=1 AND f.prod=1 AND t.hosted=1 ORDER BY t.fqdn"

select_into facilities/join/active-prod-us     "r.facility FROM topology AS t JOIN resourcegroup AS r ON t.resourcegroup = r.name JOIN factory AS f USING(fqdn) WHERE t.active=1 AND f.enabled=1 AND t.prod=1 AND f.prod=1 AND t.us=1     ORDER BY r.facility"
select_into facilities/join/active-prod-nonus  "r.facility FROM topology AS t JOIN resourcegroup AS r ON t.resourcegroup = r.name JOIN factory AS f USING(fqdn) WHERE t.active=1 AND f.enabled=1 AND t.prod=1 AND f.prod=1 AND t.us=0     ORDER BY r.facility"
select_into facilities/join/active-prod-hosted "r.facility FROM topology AS t JOIN resourcegroup AS r ON t.resourcegroup = r.name JOIN factory AS f USING(fqdn) WHERE t.active=1 AND f.enabled=1 AND t.prod=1 AND f.prod=1 AND t.hosted=1 ORDER BY r.facility"

comm -23 $topdir/facilities/topo/active-prod-us.tab $topdir/facilities/join/active-prod-us.tab > $topdir/facilities/active-prod-us-nofactory.tab
comm -23 $topdir/facilities/topo/active-prod-nonus.tab $topdir/facilities/join/active-prod-nonus.tab > $topdir/facilities/active-prod-nonus-nofactory.tab
comm -23 $topdir/facilities/topo/active-prod-hosted.tab $topdir/facilities/join/active-prod-hosted.tab > $topdir/facilities/active-prod-hosted-nofactory.tab

joined_not_factory_constraint="(SELECT COUNT(*) FROM factory WHERE factory.fqdn=joined.fqdn AND enabled=active_topology AND prod=prod_topology)=0"
joined_not_topo_constraint="(SELECT COUNT(*) FROM topology WHERE topology.fqdn=joined.fqdn AND active=active_factory AND prod=prod_factory)=0"

select_into fqdns/topo-not-fact/active-prod-us   "
	fqdn
	FROM joined
	WHERE active_topology=1
	AND prod_topology=1
	AND us=1
	AND $joined_not_factory_constraint
	ORDER BY fqdn"

select_into fqdns/topo-not-fact/active-prod-nonus "
	fqdn
	FROM joined
	WHERE active_topology=1
	AND prod_topology=1
	AND us=0
	AND $joined_not_factory_constraint
	ORDER BY fqdn"

select_into fqdns/topo-not-fact/active-prod-hosted "
	fqdn
	FROM joined
	WHERE active_topology=1
	AND prod_topology=1
	AND hosted_ce=1
	AND $joined_not_factory_constraint
	ORDER BY fqdn"

select_into fqdns/fact-not-topo/active-prod-us   "
	fqdn
	FROM joined
	WHERE active_factory=1
	AND prod_factory=1
	AND us=1
	AND $joined_not_topo_constraint
	ORDER BY fqdn"

select_into fqdns/fact-not-topo/active-prod-nonus "
	fqdn
	FROM joined
	WHERE active_factory=1
	AND prod_factory=1
	AND us=0
	AND $joined_not_topo_constraint
	ORDER BY fqdn"

select_into fqdns/fact-not-topo/active-prod-hosted "
	fqdn
	FROM joined
	WHERE active_factory=1
	AND prod_factory=1
	AND hosted_ce=1
	AND $joined_not_topo_constraint
	ORDER BY fqdn"

select_into joined -header "* FROM joined ORDER BY fqdn"
select_into joined_osgvo -header "* FROM joined WHERE vos LIKE \"%'OSGVO%\" ORDER BY fqdn"
select_into joined_prod -header "* FROM joined_prod ORDER BY fqdn"
select_into joined_prod_osgvo -header "* FROM joined_prod WHERE vos LIKE \"%'OSGVO%\" ORDER BY fqdn"



echo "results in $topdir/"
find "$topdir/fqdns" -type f -name \*.tab | sort | xargs wc -l
find "$topdir/facilities" -type f -name \*.tab | sort | xargs wc -l

# vim:noet:sw=8:sts=8:ts=8
