#!/bin/bash

cd "$(dirname "$0")"

set -e
# flock.opensciencegrid.org might be firewalled so for this one use existing data if it exists
if [[ ! -e flock_schedds.tab ]]; then
	condor_status -schedd -pool flock.opensciencegrid.org -af:t name | sort > flock_schedds.tab
else
	echo "flock_schedds.tab exists - not fetching new data"
fi

sqlite3 flock_schedds.sqlite "
	DROP TABLE IF EXISTS schedd;
	CREATE TABLE schedd(fqdn TEXT PRIMARY KEY);
"

IFS=$'\t'
while read name; do
	fqdn=`tr A-Z a-z <<<$name`
	# yeah sql injection blah blah blah
	sqlite3 flock_schedds.sqlite "INSERT INTO schedd (fqdn) VALUES ('`tr A-Z a-z <<<$fqdn`');"
done < flock_schedds.tab

# vim:noet:sw=8:sts=8:ts=8
