#!/bin/bash

cd "$(dirname "$0")"

set -e
tmpdir=$(mktemp -d)
git clone -q --depth 1 https://github.com/opensciencegrid/osg-gfactory $tmpdir/gfactory
if [[ -e gfactory.sqlite ]]; then mv -f gfactory.sqlite{,.bak}; fi
./gfactory-xml-to-db $tmpdir/gfactory
if [[ -e resources.sqlite ]]; then mv -f resources.sqlite{,.bak}; fi
./resources-to-db
if [[ -e ces.sqlite ]]; then mv -f ces.sqlite{,.bak}; fi

sqlite3 -bail ces.sqlite <<-"__END__"
	ATTACH DATABASE "gfactory.sqlite" AS gf;
	CREATE TABLE factory AS SELECT * FROM gf.entry;
	ATTACH DATABASE "resources.sqlite" AS res;
	CREATE TABLE topology AS SELECT * FROM res.ce;
	CREATE TABLE resourcegroup AS SELECT * FROM res.resourcegroup;

	CREATE VIEW joined AS
	SELECT
		topology.fqdn AS fqdn_topology,
		factory.fqdn AS fqdn_factory,
		topology.name AS resource_name,
		factory.name AS factory_entry,
		factory.gridtype AS ce_type,
		factory.gatekeeper AS contact_string,
		topology.active AS active_topology,
		factory.enabled AS active_factory,
		topology.prod AS prod_topology,
		factory.prod AS prod_factory,
		topology.us AS us,
		topology.hosted AS hosted_ce,
		r.facility AS facility
	FROM topology
	LEFT JOIN resourcegroup AS r ON topology.resourcegroup=r.name
	LEFT JOIN factory USING(fqdn)
	UNION ALL
	SELECT
		topology.fqdn AS fqdn_topology,
		factory.fqdn AS fqdn_factory,
		topology.name AS resource_name,
		factory.name AS factory_entry,
		factory.gridtype AS ce_type,
		factory.gatekeeper AS contact_string,
		topology.active AS active_topology,
		factory.enabled AS active_factory,
		topology.prod AS prod_topology,
		factory.prod AS prod_factory,
		factory.us AS us,
		factory.hosted AS hosted_ce,
		NULL AS facility
	FROM factory
	LEFT JOIN topology USING(fqdn)
	WHERE topology.fqdn IS NULL
	;

	CREATE VIEW joined_prod AS
	SELECT
		fqdn_topology,
		fqdn_factory,
		resource_name,
		factory_entry,
		ce_type,
		contact_string,
		active_topology,
		active_factory,
		us,
		hosted_ce,
		facility
	FROM joined
	WHERE (prod_topology IS NULL OR prod_topology=1)
	AND (prod_factory IS NULL OR prod_factory=1)
	;
	__END__

# vim:noet:sw=8:sts=8:ts=8
